### ISSUE TITLE
Link against openal-soft (libopenal.dylib) on OSX (instead of framework version)

### ISSUE THREAD

**Issue by venetanji** [jpernst/alto#26]
This may be kind of a pain for you, but I wonder if there is any way to give the option without needing have a whole other package. The problem is that openal-soft compiles as a dylib typically in /usr/local/lib but the openal link is specified as framework in this package so I just had to modify that one line in a local project to get it working.

**Comment by jpernst** [comment]
Sorry this slipped under my radar. I'm completely rewriting this lib, so I'll remember to look into this once it's back in a workable state.

**Comment by jpernst** [comment]
I'm reworking the sys bindings to use `dlopen` instead of a compile-time link. As part of the loading process, it will search for `libopenal.dylib` first before falling back to the framework version, so this will be fixed in the next published release.

**Comment by jpernst** [comment]
This is no longer an issue with alto, since the library is loaded dynamically, hopefully that improves the situation.
