### ISSUE TITLE
Capture not working

### ISSUE THREAD

**Issue by man0lis** [jpernst/alto#36]
I tried to use the audio capture functionality (using open_capture from Alto) and it failed with the error
`UnsupportedVersion { major: 0, minor: 0 }`

I tested this on
- Arch Linux with openal version 1.18.2
- Debian with openal version 1.17.2
- Fedora with openal version 1.18.0

Lets investigate further:
running cargo test on the alto repo also fails with the same error in the capture tests
by stepping trough alto in the debugger we find that the check_version function in alc.rs in line 221 seems to be the problem, but the code looks correct

https://github.com/jpernst/alto/blob/e22efe2e985fe064b24033cf6c7c01b8d587b5c5/src/alc.rs#L221-L234

stepping further into libopenal we arrive at the GetIntergerv function in line 3164 (current master) 

https://github.com/kcat/openal-soft/blob/d7895db166fe77bbeb360201a65a11f99693a65d/Alc/ALc.c#L3164-L3183

The code in and beyond this line suggests that getting major and minor versions for capture devices is not supported and always produces an ALC_INVALID_ENUM error. So the major and minor in check_verison are initialized with 0 but never changed. This results in the error.

Not sure what the best fix is, but my first thought was to simply remove the version check from open_capture. (or we suggest a fix in openal, but not sure how easy that would be)

**Comment by jpernst** [comment]
Thanks for digging into this. I agree that there's no great solution here, and that removing the version check on capture devices for now is probably just the best option, so I've published a new version that does that. The tests seem to pass now.

**Comment by jpernst** [comment]
Quick followup, just mentioned this to kcat on IRC and he agrees it's probably an oversight and will fix it. I'll leave the version check stubbed out for a while though since it will be some time before the fix becomes mainstream.
